In [1]:
import numpy as np

In [2]:
marks = np.array([[85, 90, 88],
                  [78, 82, 80],
                  [92, 88, 95],
                  [80, 75, 85],
                  [95, 90, 92]])

In [3]:
print("\nARRAY INFORMATION")
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Data type:", marks.dtype)
print("Total number of elements:", marks.size)


ARRAY INFORMATION
Number of dimensions: 2
Shape: (5, 3)
Data type: int64
Total number of elements: 15


In [4]:
print("\nINDEXING")
print("Python mark of Student 1:", marks[0, 0])
print("Database mark of Student 3:", marks[2, 1])
print("Web Development mark of Student 5:", marks[4, 2])


INDEXING
Python mark of Student 1: 85
Database mark of Student 3: 88
Web Development mark of Student 5: 92


In [5]:
# First 3 students
print("First 3 students:")
print(marks[:3])

First 3 students:
[[85 90 88]
 [78 82 80]
 [92 88 95]]


In [6]:
# Python marks of all students
print("\nPython marks:")
print(marks[:, 0])



Python marks:
[85 78 92 80 95]


In [7]:
print("Marks + 5:")
print(marks + 5)

Marks + 5:
[[ 90  95  93]
 [ 83  87  85]
 [ 97  93 100]
 [ 85  80  90]
 [100  95  97]]


In [8]:
print("\nMarks - 5:")
print(marks - 5)


Marks - 5:
[[80 85 83]
 [73 77 75]
 [87 83 90]
 [75 70 80]
 [90 85 87]]


In [9]:
print("\nMarks * 2:")
print(marks * 2)



Marks * 2:
[[170 180 176]
 [156 164 160]
 [184 176 190]
 [160 150 170]
 [190 180 184]]


In [12]:
student_average = np.mean(marks, axis=1)

for i in range(len(student_average)):
    print("Student", i + 1, "=", round(student_average[i], 2))

Student 1 = 87.67
Student 2 = 80.0
Student 3 = 91.67
Student 4 = 80.0
Student 5 = 92.33


In [16]:
subject_average = np.mean(marks, axis=0)

print("\nSUBJECT-WISE AVERAGES")
print("Python:", round(subject_average[0], 2))
print("Database:", round(subject_average[1], 2))
print("Web Development:", round(subject_average[2], 2))



SUBJECT-WISE AVERAGES
Python: 86.0
Database: 85.0
Web Development: 88.0


In [17]:
highest = np.max(marks)
lowest = np.min(marks)
print("Highest mark:", highest)
print("Lowest mark:", lowest)

Highest mark: 95
Lowest mark: 75


In [18]:
standard_deviation = np.std(marks)
print("Standard deviation:", round(standard_deviation, 2))

Standard deviation: 6.04


In [19]:
print("MARKS GREATER THAN 80")
print(marks[marks > 80])

MARKS GREATER THAN 80
[85 90 88 82 92 88 95 85 95 90 92]


In [20]:
one_dimensional = np.array([10, 20, 30, 40, 50, 60])

In [21]:
two_dimensional = one_dimensional.reshape(2, 3)


In [22]:
print("2-D array:")
print(two_dimensional)

2-D array:
[[10 20 30]
 [40 50 60]]


In [24]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.15417933 0.61630563 0.2364119 ]
 [0.35185257 0.01508246 0.55084608]
 [0.83970923 0.43085861 0.64462662]]


In [27]:
total_marks = np.sum(marks)
average_marks = np.mean(marks)
print("     FINAL PERFORMANCE SUMMARY\n")
print("Total marks:", total_marks)
print("Overall average:", round(average_marks, 2))
print("Highest mark:", np.max(marks))
print("Lowest mark:", np.min(marks))
print("Standard deviation:", round(np.std(marks), 2))

print("\nSubject-wise average:")
print("Python:", round(subject_average[0], 2))
print("Database:", round(subject_average[1], 2))
print("Web Development:", round(subject_average[2], 2))

print("\nStudent-wise average:")
for i, avg in enumerate(student_average):
    print("Student", i + 1, ":", round(avg, 2))

print("\nMarks greater than 80:")
print(marks[marks > 80])


     FINAL PERFORMANCE SUMMARY

Total marks: 1295
Overall average: 86.33
Highest mark: 95
Lowest mark: 75
Standard deviation: 6.04

Subject-wise average:
Python: 86.0
Database: 85.0
Web Development: 88.0

Student-wise average:
Student 1 : 87.67
Student 2 : 80.0
Student 3 : 91.67
Student 4 : 80.0
Student 5 : 92.33

Marks greater than 80:
[85 90 88 82 92 88 95 85 95 90 92]
